version: '3.8'

services:
  app:
    image: php:8.1-fpm
    container_name: app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    depends_on:
      - redis
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    entrypoint: |
      sh -c "apt-get update && apt-get install -y unzip git libzip-dev &&
      docker-php-ext-install zip && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
      php-fpm"

  webserver:
    image: nginx:alpine
    container_name: webserver
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
